"""add stock_movements.reason and adjust set-to rules

Revision ID: 1acf569a2302
Revises: 90ed817a01f0
Create Date: 2026-01-07 22:16:16.311582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acf569a2302'
down_revision = '90ed817a01f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
