"""add supplier/customer is_active

Revision ID: f68a79b0aca7
Revises: 1acf569a2302
Create Date: 2026-01-07 22:59:42.295452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68a79b0aca7'
down_revision = '1acf569a2302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
